name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-focal
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npm run test
      env:
        CI: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: results/html-report/
        retention-days: 30

    - name: Upload test videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-videos
        path: reports/
        retention-days: 7

  test-components:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-focal
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run component tests
      run: npm run test:component
      continue-on-error: true  # Component tests might not be implemented yet

    - name: Upload component test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: component-test-report
        path: results/
        retention-days: 7